@startuml Usecase
left to right direction
actor User
rectangle "Shino Cactus" as ShinoCactus{
    note "Usecase Description Status\nPink: Not available\nYellow: Uncompleted" as CommonNote

    usecase Overview #Yellow
    usecase Notifications #Yellow
    usecase "Pot Changing" as PotC #pink
    usecase Water #pink
    usecase Fertilizing #pink 
    usecase "Adding Pesticides" as APesticides #pink
    usecase "Plan Management" as PlanM #pink
    usecase Plant #pink
    usecase Care #pink
    usecase "Growing Mix Management" as GXM
    usecase "Growing Media Management" as GMM #pink
    usecase "Pot Management" as PotM #pink
    usecase "Fertilizer Management" as FertilizerM #pink
    usecase "Pesticide Management" as PesticideM #pink
}

User --> Overview
User --> Notifications
User --> PotC
User --> Water
User --> Fertilizing
User --> APesticides
User --> PlanM
User --> GXM
User --> GMM
User --> PotM
User --> FertilizerM
User --> PesticideM

PlanM ..> Plant : <<Extend>>
PlanM ..> Care : <<Extend>>
@enduml