@startuml Usecase
left to right direction
actor User
rectangle "Shino Cactus" as ShinoCactus{
    note "Usecase Description Status\nPink: Not available\nYellow: Uncompleted" as CommonNote
    note "Each usecase description\nsame Growing Media Management\nrefer Usecase 2.2" as SameDesc

    usecase Overview #Yellow
    usecase Notifications #Yellow
    usecase "Pot Changing" as PotC #pink
    usecase Water #pink
    usecase Fertilizing #pink 
    usecase "Adding Pesticides" as APesticides #pink
    usecase "Planning" as PlanM #pink
    usecase Planting #pink
    usecase Care #pink
    usecase "Growing Mix Management" as GXM
    usecase "Growing Media Management" as GMM
    usecase "Pot Management" as PotM #darkgrey
    usecase "Fertilizer Management" as FertilizerM #darkgrey
    usecase "Pesticide Management" as PesticideM #darkgrey

}

User --> Overview
User --> Notifications
User --> PotC
User --> Water
User --> Fertilizing
User --> APesticides
User --> PlanM
User --> Planting
User --> Care
User --> GXM
User --> GMM
User --> PotM
User --> FertilizerM
User --> PesticideM

PlanM .right.> Planting : <<Extend>>
PlanM .left.> Care : <<Extend>>

GMM .. SameDesc
PotM .. SameDesc
FertilizerM .. SameDesc
PesticideM .. SameDesc
@enduml